#!/usr/bin/env python3
"""Rebuild the portfolio showcase from data/projects.toml.

    python scripts/build.py              # ingest new uploads, rebuild heroes, pages and README blocks
    python scripts/build.py --keep-raw   # same, but leave the raw uploads in assets/

Drop zone:  assets/<PREFIX>_<N>.png|jpg|jpeg|webp|gif   (PREFIX is set per project in the manifest)
Needs:      Python 3.11+ and Pillow  (pip install pillow)
"""
import argparse
import hashlib
import html
import json
import re
import shutil
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageOps

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
OUT = ASSETS / "projects"
PAGES = ROOT / "projects"
README = ROOT / "README.md"
MANIFEST = ROOT / "data" / "projects.toml"
CACHE = OUT / ".build-cache.json"

GENERATED = "<!-- generated by scripts/build.py from data/projects.toml - edit the manifest, not this file -->"
RAW_EXT = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
RAW_NAME = re.compile(r"^([A-Za-z]+)[ _-]*(\d+)$")
MAX_W, PHONE_MAX_W, QUALITY = 1600, 720, 84
PHONE_RATIO, WIDE_RATIO = 0.7, 2.2
GIF_WARN_MB = 5
HERO_W, HERO_H = 1600, 900
HERO_VERSION = 1  # bump when the hero drawing code changes, so cached heroes are rebuilt


def fail(msg):
    sys.exit(f"error: {msg}")


def esc(text):
    return html.escape(str(text), quote=True)


# ---------------------------------------------------------------- manifest

def load_manifest():
    if not MANIFEST.is_file():
        fail(f"{MANIFEST.relative_to(ROOT)} not found")
    projects = tomllib.loads(MANIFEST.read_text("utf-8")).get("project", [])
    slugs, prefixes = set(), set()
    for p in projects:
        for key in ("slug", "prefix", "kind", "title", "summary"):
            if not p.get(key):
                fail(f"project '{p.get('slug', p.get('title', '?'))}' is missing '{key}' in data/projects.toml")
        if p["kind"] not in ("product", "academic"):
            fail(f"project '{p['slug']}': kind must be \"product\" or \"academic\"")
        p["prefix"] = p["prefix"].upper()
        for key, owner in (("slug", slugs), ("prefix", prefixes)):
            if p[key] in owner:
                fail(f"duplicate {key} '{p[key]}' in data/projects.toml")
            owner.add(p[key])
        p.setdefault("tech", [])
        p.setdefault("tagline", "")
        for key in ("captions", "trim_bottom", "redact"):
            p.setdefault(key, {})
        p.setdefault("bg", ["#0d1117", "#1b2230"])
        p.setdefault("accent", "#7aa2f7")
    return projects


# ---------------------------------------------------------------- ingest

def flatten(im):
    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")
        base = Image.new("RGB", im.size, "white")
        base.paste(im, mask=im.getchannel("A"))
        return base
    return im.convert("RGB")


def redact(im, box):
    """Paint over a region, blending the colours just left and right of it row by row."""
    x0, y0, x1, y1 = (int(v) for v in box)
    px, w = im.load(), im.width
    xl, xr = max(x0 - 1, 0), min(x1, w - 1)
    for y in range(y0, y1):
        cl, cr = px[xl, y], px[xr, y]
        for x in range(x0, x1):
            t = (x - xl) / max(xr - xl, 1)
            px[x, y] = tuple(round(cl[i] * (1 - t) + cr[i] * t) for i in range(3))


def process_raw(src, project, n):
    dest_dir = OUT / project["slug"]
    dest_dir.mkdir(parents=True, exist_ok=True)
    if src.suffix.lower() == ".gif":
        dest = dest_dir / f"{n:02d}.gif"
        shutil.copyfile(src, dest)
        (dest_dir / f"{n:02d}.webp").unlink(missing_ok=True)
        mb = dest.stat().st_size / 1024 / 1024
        note = f"  <-- over {GIF_WARN_MB} MB, consider trimming it" if mb > GIF_WARN_MB else ""
        print(f"  {dest.relative_to(ROOT)}  {mb:.1f} MB (gif kept as-is){note}")
        return dest

    im = flatten(ImageOps.exif_transpose(Image.open(src)))
    trim = project["trim_bottom"].get(str(n))
    if trim:
        im = im.crop((0, 0, im.width, im.height - int(trim)))
    for box in project["redact"].get(str(n), []):
        redact(im, box)
    limit = PHONE_MAX_W if im.width / im.height < PHONE_RATIO else MAX_W
    if im.width > limit:
        im = im.resize((limit, round(im.height * limit / im.width)), Image.LANCZOS)
    dest = dest_dir / f"{n:02d}.webp"
    im.save(dest, "WEBP", quality=QUALITY, method=6)  # no exif passed: location/camera metadata is dropped
    (dest_dir / f"{n:02d}.gif").unlink(missing_ok=True)
    print(f"  {dest.relative_to(ROOT)}  {dest.stat().st_size // 1024} KB")
    return dest


def ingest(projects, keep_raw):
    by_prefix = {p["prefix"]: p for p in projects}
    claimed, count = {}, 0
    for src in sorted(ASSETS.iterdir()):
        if not src.is_file() or src.suffix.lower() not in RAW_EXT:
            continue
        m = RAW_NAME.match(src.stem)
        if not m:
            print(f"skipped assets/{src.name}: name must look like PREFIX_N (e.g. LA_1.png)")
            continue
        project = by_prefix.get(m.group(1).upper())
        if not project:
            print(f"skipped assets/{src.name}: no project in data/projects.toml uses prefix '{m.group(1).upper()}'")
            continue
        n = int(m.group(2))
        key = (project["slug"], n)
        if key in claimed:
            print(f"warning: assets/{src.name} and assets/{claimed[key]} are both {project['prefix']}_{n}; the later one wins")
        claimed[key] = src.name
        if count == 0:
            print("Ingesting uploads:")
        process_raw(src, project, n)
        if not keep_raw:
            src.unlink()
        count += 1
    return count


# ---------------------------------------------------------------- shots

@dataclass
class Shot:
    n: int
    path: Path
    w: int
    h: int
    caption: str

    @property
    def ratio(self):
        return self.w / self.h


def collect_shots(project):
    folder = OUT / project["slug"]
    found = {}
    if folder.is_dir():
        for f in folder.iterdir():
            m = re.fullmatch(r"(\d\d)\.(webp|gif)", f.name)
            if m and (int(m.group(1)) not in found or f.stat().st_mtime > found[int(m.group(1))].stat().st_mtime):
                found[int(m.group(1))] = f
    shots = []
    for n in sorted(found):
        with Image.open(found[n]) as im:
            w, h = im.size
        shots.append(Shot(n, found[n], w, h, project["captions"].get(str(n), f"Screenshot {n}")))
    return shots


# ---------------------------------------------------------------- hero collage

SLOTS = {
    "cascade": [((90, 80, 1120, 640), "nw"), ((70, 520, 760, 850), "sw"), ((760, 300, 1530, 840), "se")],
    "device": [((70, 150, 1010, 760), "c"), ((930, 170, 1300, 860), "s"), ((1200, 60, 1560, 770), "n")],
    "phones": [((130, 130, 560, 800), "c"), ((580, 60, 1010, 780), "c"), ((1030, 140, 1470, 810), "c")],
}


def hex_rgb(value):
    value = value.lstrip("#")
    return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4))


def background(bg, accent):
    c1, c2 = (hex_rgb(c) for c in bg)
    vert = Image.linear_gradient("L").resize((HERO_W, HERO_H))
    horiz = Image.linear_gradient("L").rotate(90).resize((HERO_W, HERO_H))
    mask = ImageChops.add(vert, horiz, scale=2)
    canvas = Image.composite(Image.new("RGB", mask.size, c2), Image.new("RGB", mask.size, c1), mask)
    for cx, cy, radius, alpha in ((1350, 120, 760, 0.55), (180, 820, 620, 0.30)):
        fall = ImageOps.invert(Image.radial_gradient("L")).resize((2 * radius, 2 * radius))
        fall = fall.point(lambda v, a=alpha: int(255 * (v / 255) ** 2 * a))
        canvas.paste(Image.new("RGB", fall.size, hex_rgb(accent)), (cx - radius, cy - radius), fall)
    dots = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(dots)
    for y in range(24, HERO_H, 36):
        for x in range(24, HERO_W, 36):
            d.ellipse((x - 1, y - 1, x + 1, y + 1), fill=(255, 255, 255, 22))
    return Image.alpha_composite(canvas.convert("RGBA"), dots).convert("RGB")


def window(im, size, radius=18):
    ss = 3
    im = im.convert("RGB").resize(size, Image.LANCZOS).convert("RGBA")
    big = (size[0] * ss, size[1] * ss)
    mask = Image.new("L", big, 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, big[0] - 1, big[1] - 1), radius * ss, fill=255)
    ring = Image.new("L", big, 0)
    ImageDraw.Draw(ring).rounded_rectangle((0, 0, big[0] - 1, big[1] - 1), radius * ss, outline=255, width=2 * ss)
    mask, ring = mask.resize(size, Image.LANCZOS), ring.resize(size, Image.LANCZOS).point(lambda v: v * 80 // 255)
    edge = Image.new("RGBA", size, (255, 255, 255, 255))
    edge.putalpha(ring)
    im.putalpha(mask)
    return Image.alpha_composite(im, edge)


def drop_shadow(canvas, x, y, size, radius=18, blur=34, dy=26, opacity=0.6):
    pad = blur * 3
    layer = Image.new("L", (size[0] + 2 * pad, size[1] + 2 * pad), 0)
    ImageDraw.Draw(layer).rounded_rectangle((pad, pad, pad + size[0], pad + size[1]), radius, fill=int(255 * opacity))
    layer = layer.filter(ImageFilter.GaussianBlur(blur))
    canvas.paste((0, 0, 0), (x - pad, y - pad + dy), layer)


def fit(box, size, anchor):
    bx0, by0, bx1, by1 = box
    scale = min((bx1 - bx0) / size[0], (by1 - by0) / size[1])
    w, h = round(size[0] * scale), round(size[1] * scale)
    fx = 0 if "w" in anchor else 1 if "e" in anchor else 0.5
    fy = 0 if "n" in anchor else 1 if "s" in anchor else 0.5
    return bx0 + round((bx1 - bx0 - w) * fx), by0 + round((by1 - by0 - h) * fy), (w, h)


def make_hero(project, shots, dest):
    by_n = {s.n: s for s in shots}
    wanted = [by_n[n] for n in project.get("hero", []) if n in by_n] or shots[:3]
    wanted = wanted[:3]
    phones = [s for s in wanted if s.ratio < PHONE_RATIO]
    desktops = [s for s in wanted if s.ratio >= PHONE_RATIO]
    if phones and desktops:
        layout, order = "device", desktops[:1] + phones[:2]
    elif phones:
        layout, order = "phones", phones
    else:
        layout, order = "cascade", desktops
    canvas = background(project["bg"], project["accent"])
    slots = SLOTS[layout]
    for shot, (box, anchor) in zip(order, slots):
        with Image.open(shot.path) as src:
            src = src.convert("RGB")
        x, y, size = fit(box, src.size, anchor)
        drop_shadow(canvas, x, y, size)
        win = window(src, size)
        canvas.paste(win, (x, y), win)
    canvas.save(dest, "WEBP", quality=82, method=6)
    return layout


def build_heroes(projects, shots_by_slug):
    cache = json.loads(CACHE.read_text("utf-8")) if CACHE.is_file() else {}
    fresh = {}
    for p in projects:
        shots = shots_by_slug[p["slug"]]
        if not shots:
            continue
        dest = OUT / p["slug"] / "hero.webp"
        sig = hashlib.sha256(json.dumps([
            HERO_VERSION, p["bg"], p["accent"], p.get("hero", []),
            [(s.n, hashlib.sha256(s.path.read_bytes()).hexdigest()) for s in shots],
        ]).encode()).hexdigest()
        fresh[p["slug"]] = sig
        if cache.get(p["slug"]) == sig and dest.is_file():
            continue
        layout = make_hero(p, shots, dest)
        print(f"hero: {dest.relative_to(ROOT)} ({layout}, {dest.stat().st_size // 1024} KB)")
    if fresh != cache:
        CACHE.write_text(json.dumps(fresh, indent=2, sort_keys=True) + "\n", "utf-8")


# ---------------------------------------------------------------- gallery layout

def layout_rows(shots):
    """Numeric order is kept. Phones share a row (up to 4), wide strips get their own row,
    and neighbours of similar shape pair up; anything else gets a full-width row."""
    rows, i = [], 0
    while i < len(shots):
        s = shots[i]
        if s.ratio < PHONE_RATIO:
            group = [s]
            while i + len(group) < len(shots) and shots[i + len(group)].ratio < PHONE_RATIO and len(group) < 4:
                group.append(shots[i + len(group)])
            rows.append(("phones", group))
            i += len(group)
        elif s.ratio >= WIDE_RATIO:
            rows.append(("wide", [s]))
            i += 1
        else:
            nxt = shots[i + 1] if i + 1 < len(shots) else None
            if nxt and PHONE_RATIO <= nxt.ratio < WIDE_RATIO and max(s.ratio, nxt.ratio) / min(s.ratio, nxt.ratio) <= 1.4:
                rows.append(("pair", [s, nxt]))
                i += 2
            else:
                rows.append(("single", [s]))
                i += 1
    return rows


def cell(slug, shot, width, td_width=None):
    cap = esc(shot.caption)
    td = f' width="{td_width}"' if td_width else ""
    return (f'<td align="center" valign="top"{td}><img src="../assets/projects/{slug}/{shot.path.name}" '
            f'width="{width}" alt="{cap}"><br><sub>{cap}</sub></td>')


def row_html(slug, kind, group):
    if kind == "phones":
        full = len(group) == 4
        cells = [cell(slug, s, "100%" if full else 190, "25%" if full else None) for s in group]
    elif kind == "pair":
        cells = [cell(slug, s, "100%", "50%") for s in group]
    else:
        s = group[0]
        width = "100%" if s.ratio >= 1.2 else round(720 * s.ratio)
        cells = [cell(slug, s, width)]
    return "<table>\n<tr>\n" + "\n".join(cells) + "\n</tr>\n</table>"


# ---------------------------------------------------------------- pages

def tech_line(tech):
    return " ".join(f"`{t}`" for t in tech)


def link_line(p):
    bits = []
    if p.get("live"):
        bits.append(f"**Live:** [{re.sub(r'^https?://|/$', '', p['live'])}]({p['live']})")
    if p.get("repo"):
        bits.append(f"**Code:** [{re.sub(r'^https?://', '', p['repo'])}]({p['repo']})")
    return "  \n".join(bits)


def page_markdown(p, shots, prev_p, next_p):
    slug = p["slug"]
    out = [GENERATED, "", "[← Back to profile](../README.md#featured-work)", "", f"# {p['title']}", ""]
    if (OUT / slug / "hero.webp").is_file():
        out += [f'<p align="center"><img src="../assets/projects/{slug}/hero.webp" alt="{esc(p["title"])} screenshots" width="100%"></p>', ""]
    if p["tagline"]:
        out += [f"**{p['tagline']}**", ""]
    out += [p["summary"], ""]
    meta = [m for m in (f"**Stack:** {tech_line(p['tech'])}" if p["tech"] else "", link_line(p)) if m]
    if meta:
        out += ["  \n".join(meta), ""]
    out += [f"## Screenshots ({len(shots)})", ""]
    out += ["\n\n".join(row_html(slug, k, g) for k, g in layout_rows(shots)), ""]
    nav = []
    if prev_p:
        nav.append(f"[← {prev_p['title']}]({prev_p['slug']}.md)")
    nav.append("[All projects](../README.md#featured-work)")
    if next_p:
        nav.append(f"[{next_p['title']} →]({next_p['slug']}.md)")
    out += ["---", "", " · ".join(nav), ""]
    return "\n".join(out)


def write_pages(projects, shots_by_slug):
    PAGES.mkdir(exist_ok=True)
    with_pages = [p for p in projects if shots_by_slug[p["slug"]]]
    wanted = set()
    for i, p in enumerate(with_pages):
        prev_p = with_pages[i - 1] if i else None
        next_p = with_pages[i + 1] if i + 1 < len(with_pages) else None
        dest = PAGES / f"{p['slug']}.md"
        text = page_markdown(p, shots_by_slug[p["slug"]], prev_p, next_p)
        if not dest.is_file() or dest.read_text("utf-8") != text:
            dest.write_text(text, "utf-8")
            print(f"page: {dest.relative_to(ROOT)} ({len(shots_by_slug[p['slug']])} screenshots)")
        wanted.add(dest.name)
    for old in PAGES.glob("*.md"):  # only ever remove pages this script generated
        if old.name not in wanted and old.read_text("utf-8").startswith(GENERATED):
            old.unlink()
            print(f"removed stale page: {old.relative_to(ROOT)}")
    return {p["slug"] for p in with_pages}


# ---------------------------------------------------------------- README blocks

def card(p, shots, has_page, colspan):
    slug = p["slug"]
    page = f"projects/{slug}.md"
    img = ""
    if (OUT / slug / "hero.webp").is_file():
        pic = f'<img src="assets/projects/{slug}/hero.webp" alt="{esc(p["title"])} screenshots" width="100%">'
        img = f'  <a href="{page}">{pic}</a>\n' if has_page else f"  {pic}\n"
    links = []
    if p.get("live"):
        links.append(f'<a href="{esc(p["live"])}"><b>Live app ↗</b></a>')
    if p.get("repo"):
        links.append(f'<a href="{esc(p["repo"])}">Code</a>')
    if has_page:
        links.append(f'<a href="{page}">Gallery · {len(shots)} screens</a>')
    tech = " ".join(f"<code>{esc(t)}</code>" for t in p["tech"])
    span = ' colspan="2"' if colspan else ' width="50%"'
    return (f'<td{span} valign="top">\n{img}  <h3>{esc(p["title"])}</h3>\n  <p>{esc(p["summary"])}</p>\n'
            f'  <p>{tech}</p>\n  <p>{" · ".join(links)}</p>\n</td>')


def featured_block(products, shots_by_slug, pages):
    rows = []
    for i in range(0, len(products), 2):
        pair = products[i:i + 2]
        cells = [card(p, shots_by_slug[p["slug"]], p["slug"] in pages, len(pair) == 1) for p in pair]
        rows.append("<tr>\n" + "\n".join(cells) + "\n</tr>")
    return "<table>\n" + "\n".join(rows) + "\n</table>"


def academic_block(items, shots_by_slug, pages):
    linked = any(p.get("repo") or p["slug"] in pages for p in items)
    head = "| Project | What it does | Stack |" + (" Links |" if linked else "")
    rule = "|---|---|---|" + ("---|" if linked else "")
    lines = [head, rule]
    for p in items:
        links = []
        if p["slug"] in pages:
            links.append(f"[Gallery](projects/{p['slug']}.md)")
        if p.get("repo"):
            links.append(f"[Code]({p['repo']})")
        row = f"| **{p['title']}** | {p['summary']} | {tech_line(p['tech'])} |"
        lines.append(row + (f" {' · '.join(links)} |" if linked else ""))
    return "\n".join(lines)


def replace_block(text, name, body):
    pattern = re.compile(rf"(<!-- {name}:start -->).*?(<!-- {name}:end -->)", re.S)
    if not pattern.search(text):
        fail(f"README.md needs <!-- {name}:start --> and <!-- {name}:end --> markers")
    return pattern.sub(lambda m: f"{m.group(1)}\n{body}\n{m.group(2)}", text, count=1)


def update_readme(projects, shots_by_slug, pages):
    products = [p for p in projects if p["kind"] == "product"]
    academic = [p for p in projects if p["kind"] == "academic"]
    text = README.read_text("utf-8")
    text = replace_block(text, "featured", featured_block(products, shots_by_slug, pages))
    text = replace_block(text, "academic", academic_block(academic, shots_by_slug, pages))
    live = sum(1 for p in products if p.get("live"))
    text = re.sub(r"<!--live-->.*?<!--/live-->", f"<!--live-->{live}<!--/live-->", text)
    if text != README.read_text("utf-8"):
        README.write_text(text, "utf-8")
        print("README.md updated")


# ---------------------------------------------------------------- main

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--keep-raw", action="store_true", help="don't delete raw uploads from assets/ after ingesting")
    args = parser.parse_args()

    projects = load_manifest()
    ingested = ingest(projects, args.keep_raw)
    shots_by_slug = {p["slug"]: collect_shots(p) for p in projects}
    build_heroes(projects, shots_by_slug)
    pages = write_pages(projects, shots_by_slug)
    update_readme(projects, shots_by_slug, pages)
    total = sum(len(s) for s in shots_by_slug.values())
    print(f"done: {len(projects)} projects, {total} screenshots, {ingested} new upload(s)")


if __name__ == "__main__":
    main()
